typography_spectrum: 0.4682073653675616
color:
  brandStrength: 0.8953866183292121
  lightness: 0.9337457809597254
  saturation: 0.4176895138807595
  rhythmicContrast: 0.006243386538699269
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.8617065965663642
author:
  name: Roberto
  email: roberto@priceonvalue.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/72a20787-38e7-43ef-9d72-ce51ed545262.png
name: PricingNerd
title: Capture the Value of Your Differentiation
